-- Fictional identities only; every change (including any reset) is rolled back.
begin;
set local plpgsql.check_asserts=on;
set local lock_timeout='3s';
set local statement_timeout='25s';
do $$
declare
  a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); c uuid:=gen_random_uuid();
  ta uuid:=gen_random_uuid(); tb uuid:=gen_random_uuid(); tc uuid:=gen_random_uuid();
  ka text:='guest:'||a; kb text:='guest:'||b; kc text:='guest:'||c;
  req uuid:=gen_random_uuid(); req2 uuid:=gen_random_uuid(); req3 uuid:=gen_random_uuid(); req4 uuid:=gen_random_uuid();
  p public.secret_mission_players%rowtype; result jsonb; m uuid; assigned timestamptz; scoreboard_version text;
begin
  insert into public.guests(id,name,status) values(a,'QA Mission Author','confirmed'),(b,'QA Mission Witness','confirmed'),(c,'QA Mission Other','confirmed');
  update public.party_state set phase='preparation',missions_visible=true where id='main';
  set local role anon;
  assert public.claim_party_identity(ka,ta)->>'ok'='true';
  assert public.claim_party_identity(kb,tb)->>'ok'='true';
  assert public.claim_party_identity(kc,tc)->>'ok'='true';
  result:=public.claim_secret_mission(ka,ta);
  assert result->>'ok'='true';
  m:=(result->'mission'->>'id')::uuid; assigned:=(result->'mission'->>'assignedAt')::timestamptz;
  assert m is not null;
  assert public.complete_secret_mission(ka,ta,m)->>'code'='VALIDATION_REQUIRED','Legacy self-award disabled';
  assert public.request_secret_mission_check(ka,null,m,assigned,kb,req)->>'code'='INVALID_SESSION';
  assert public.request_secret_mission_check(ka,tc,m,assigned,kb,req)->>'code'='INVALID_SESSION';
  assert public.request_secret_mission_check(ka,ta,m,assigned,ka,req)->>'code'='SELF_VALIDATION';
  assert public.request_secret_mission_check(ka,ta,m,assigned,'guest:'||gen_random_uuid(),req)->>'code'='REVIEWER_UNAVAILABLE';
  assert public.request_secret_mission_check(ka,ta,m,assigned-interval '1 second',kb,req)->>'code'='STALE_MISSION';
  assert public.request_secret_mission_check(ka,ta,m,assigned,kb,req)->>'ok'='true';
  assert public.request_secret_mission_check(ka,ta,m,assigned,kb,req)->>'ok'='true','Retry is idempotent';
  assert public.request_secret_mission_check(ka,ta,m,assigned,kc,req2)->>'code'='VALIDATION_PENDING';
  assert public.get_secret_mission_checks(ka,ta)->'own'->>'status'='pending';
  result:=public.get_secret_mission_checks(kb,tb,true);
  assert (result->>'incomingCount')::int=1 and not result ? 'incoming','Summary has no secret';
  assert jsonb_array_length(public.get_secret_mission_checks(kb,tb)->'incoming')=1;
  assert jsonb_array_length(public.get_secret_mission_checks(kc,tc)->'incoming')=0,'Only the chosen witness sees it';
  assert public.decide_secret_mission_check(ka,ta,req,true)->>'ok'='false';
  assert public.decide_secret_mission_check(kc,tc,req,true)->>'code'='NOT_REVIEWER';
  assert public.decide_secret_mission_check(kb,null,req,true)->>'code'='INVALID_SESSION';
  assert public.cancel_secret_mission_check(kc,tc,req)->>'ok'='false';
  reset role;
  select * into p from public.secret_mission_players where player_key=ka;
  assert p.completed_count=0 and p.current_prompt_id=m,'Request never awards or changes mission';
  assert (select count(*) from party_missions.validations where player_id=p.id)=1;
  select ctid::text into scoreboard_version from public.secret_mission_scoreboard where player_id=p.id;
  perform public.get_secret_mission_state(ka,ta);
  perform public.get_secret_mission_state(ka,ta);
  assert (select ctid::text from public.secret_mission_scoreboard where player_id=p.id)=scoreboard_version,'Polling must not rewrite or rebroadcast the scoreboard';
  assert not has_table_privilege('anon','party_missions.validations','select');
  assert not has_table_privilege('authenticated','party_missions.validations','insert');
  assert not has_function_privilege('anon','public.private_assign_secret_mission(uuid)','execute');
  assert not has_function_privilege('anon','party_missions.cancel_stale()','execute');
  update public.party_state set phase='ended' where id='main';
  assert public.decide_secret_mission_check(kb,tb,req,true)->>'code'='MISSIONS_CLOSED';
  update public.party_state set phase='preparation' where id='main';
  set local role anon;
  assert public.decide_secret_mission_check(kb,tb,req,true)->>'ok'='true';
  assert public.decide_secret_mission_check(kb,tb,req,true)->>'ok'='true','Duplicate approval is harmless';
  assert public.decide_secret_mission_check(kb,tb,req,false)->>'ok'='false';
  reset role;
  select * into p from public.secret_mission_players where player_key=ka;
  assert p.completed_count=1;
  assert (select completed_count from public.secret_mission_scoreboard where player_id=p.id)=1;
  assert (select count(*) from public.secret_mission_history where player_id=p.id and outcome='completed')=1;
  assert (select status from party_missions.validations where id=req)='approved';
  m:=p.current_prompt_id; assigned:=p.assigned_at;
  set local role anon;
  assert public.request_secret_mission_check(ka,ta,m,assigned,kb,req2)->>'ok'='true';
  assert public.decide_secret_mission_check(kb,tb,req2,false)->>'ok'='true';
  assert public.get_secret_mission_checks(ka,ta)->'own'->>'status'='rejected';
  assert public.request_secret_mission_check(ka,ta,m,assigned,kc,req3)->>'ok'='true';
  assert public.cancel_secret_mission_check(ka,ta,req3)->>'ok'='true';
  assert public.decide_secret_mission_check(kc,tc,req3,true)->>'ok'='false';
  reset role;
  select * into p from public.secret_mission_players where player_key=ka;
  assert p.completed_count=1 and p.current_prompt_id=m and p.skips_used=0,'Reject/cancel preserve mission and joker';
  set local role anon;
  assert public.request_secret_mission_check(ka,ta,m,assigned,kb,req4)->>'ok'='true';
  assert public.skip_secret_mission(ka,ta,m)->>'ok'='true';
  assert public.decide_secret_mission_check(kb,tb,req4,true)->>'ok'='false','Skipping invalidates witness request';
  reset role;
  assert (select status from party_missions.validations where id=req4)='cancelled';
  assert (select completed_count from public.secret_mission_players where player_key=ka)=1;
  insert into party_identity.revoked_tokens(session_token) values(tb);
  assert public.get_secret_mission_checks(kb,tb)->>'code'='INVALID_SESSION';
  assert public.decide_secret_mission_check(kb,tb,req,true)->>'code'='INVALID_SESSION';
  -- Admin data reset already removes mission players. Its FK cascade removes all checks.
  delete from public.secret_mission_players where id=p.id;
  assert not exists(select 1 from party_missions.validations where player_id=p.id);
end;
$$;
rollback;
