-- All fixtures and state changes are rolled back. Run as the project database owner.
begin;
do $$
declare
 a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); c uuid:=gen_random_uuid();
 ta uuid:=gen_random_uuid(); tb uuid:=gen_random_uuid(); tc uuid:=gen_random_uuid();
 ka text; kb text; kc text; admin_id uuid; payload jsonb; song uuid; duo uuid;
 denied boolean:=false;
begin
 ka:='guest:'||a; kb:='guest:'||b; kc:='guest:'||c;
 select user_id into admin_id from public.app_admins limit 1;
 assert admin_id is not null,'Test requires existing admin';
 insert into public.guests(id,name,status) values(a,'QA Extras A','confirmed'),(b,'QA Extras B','confirmed'),(c,'QA Extras C','confirmed');
 insert into public.party_identity_sessions(player_key,player_name,session_token) values(ka,'QA Extras A',ta),(kb,'QA Extras B',tb),(kc,'QA Extras C',tc);
 update public.party_state set phase='live' where id='main';
 update party_extras.settings set capsule_reveal_at=now()+interval '1 year';
 set local role anon;
 perform set_config('request.jwt.claim.sub','',true);
 begin perform * from party_extras.letters; exception when insufficient_privilege then denied:=true; end;
 assert denied,'Private tables must deny direct reads';
 denied:=false;
 begin perform public.get_party_extras(ka,tb); exception when others then denied:=sqlerrm='IDENTITY_REQUIRED'; end;
 assert denied,'Wrong guest token must fail';
 denied:=false;
 begin perform public.party_extras_action('admin_credits'); exception when others then denied:=sqlerrm='NOT_ADMIN'; end;
 assert denied,'Guests cannot administer';
 perform public.party_extras_action('capsule_save','{"message":"Private QA message","memory":"QA memory"}',ka,ta);
 assert public.get_party_extras(ka,ta)#>>'{capsule,own,message}'='Private QA message','Author sees own letter';
 assert public.get_party_extras(kb,tb)#>'{capsule,own}'='null'::jsonb,'Other guest cannot see letter';
 assert public.get_party_extras()#>'{capsule,entries}'='[]'::jsonb,'Anonymous capsule must stay private';
 set local role authenticated;
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 assert jsonb_array_length(public.get_party_extras()#>'{capsule,entries}')=0,'Admin cannot read before reveal';
 perform public.party_extras_action('admin_settings','{"capsule_timing":"next_birthday"}');
 assert public.get_party_extras()#>>'{settings,capsule_reveal_at}' like '2027-10-24%','Opening preset applied';
 reset role;
 update party_extras.settings set capsule_reveal_at=now()-interval '1 second';
 set local role authenticated;
 assert jsonb_array_length(public.get_party_extras()#>'{capsule,entries}')>=1,'Admin can read after reveal';
 set local role anon;
 perform set_config('request.jwt.claim.sub','',true);
 assert public.get_party_extras()#>'{capsule,entries}'='[]'::jsonb,'Opened capsule still not public';
 denied:=false;
 begin perform public.party_extras_action('capsule_save','{"message":"late"}',ka,ta); exception when others then denied:=sqlerrm='CAPSULE_CLOSED'; end;
 assert denied,'Opened capsule cannot be edited';
 perform public.party_extras_action('song_submit',jsonb_build_object('title',a::text,'artist','QA artist'),ka,ta);
 select (s->>'id')::uuid into song from jsonb_array_elements(public.get_party_extras(ka,ta)->'songs') s where s->>'title'=a::text;
 assert not exists(select 1 from jsonb_array_elements(public.get_party_extras(kb,tb)->'songs') s where s->>'id'=song::text),'Pending song hidden from other guests';
 denied:=false;
 begin perform public.party_extras_action('song_vote',jsonb_build_object('id',song,'voted',true),ka,ta); exception when others then denied:=sqlerrm='VOTE_CLOSED'; end;
 assert denied,'Cannot vote for pending songs';
 denied:=false;
 begin perform public.party_extras_action('song_submit',jsonb_build_object('title',a::text,'artist','QA artist'),kb,tb); exception when others then denied:=sqlerrm='SONG_EXISTS'; end;
 assert denied,'Duplicate song rejected';
 denied:=false;
 begin perform public.party_extras_action('song_submit','{"title":"Bad","artist":"QA","link":"javascript:alert(1)"}',ka,ta); exception when others then denied:=sqlerrm='INVALID_LINK'; end;
 assert denied,'Unsafe link rejected';
 set local role authenticated;
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 perform public.party_extras_action('admin_song',jsonb_build_object('id',song,'status','queued'));
 set local role anon;
 perform set_config('request.jwt.claim.sub','',true);
 perform public.party_extras_action('song_vote',jsonb_build_object('id',song,'voted',true),ka,ta);
 perform public.party_extras_action('song_vote',jsonb_build_object('id',song,'voted',true),ka,ta);
 select s into payload from jsonb_array_elements(public.get_party_extras()->'songs') s where s->>'id'=song::text;
 assert (payload->>'votes')::integer=1,'Repeated vote is idempotent';
 perform public.party_extras_action('song_vote',jsonb_build_object('id',song,'voted',false),ka,ta);
 select s into payload from jsonb_array_elements(public.get_party_extras()->'songs') s where s->>'id'=song::text;
 assert (payload->>'votes')::integer=0,'Vote can be withdrawn';
 perform public.party_extras_action('song_submit',jsonb_build_object('title',b::text,'artist','QA artist'),ka,ta);
 perform public.party_extras_action('song_submit',jsonb_build_object('title',c::text,'artist','QA artist'),ka,ta);
 denied:=false;
 begin perform public.party_extras_action('song_submit','{"title":"Fourth","artist":"QA"}',ka,ta); exception when others then denied:=sqlerrm='SONG_LIMIT'; end;
 assert denied,'Three song quota enforced';
 perform public.party_extras_action('duo_join','{}',ka,ta);
 assert (public.get_party_extras(ka,ta)->>'waiting')::boolean,'First player waits';
 perform public.party_extras_action('duo_join','{}',kb,tb);
 payload:=public.get_party_extras(ka,ta)->'duo'; duo:=(payload->>'id')::uuid;
 assert payload->>'partner'='QA Extras B','Two volunteers paired';
 assert public.get_party_extras(kb,tb)#>>'{duo,id}'=duo::text,'Pair is shared';
 perform public.party_extras_action('duo_join','{}',ka,ta);
 assert (public.get_party_extras(ka,ta)->>'duo_attempts')::integer=1,'Repeated join is idempotent';
 denied:=false;
 begin perform public.party_extras_action('duo_confirm',jsonb_build_object('id',duo),kc,tc); exception when others then denied:=sqlerrm='DUO_NOT_ACTIVE'; end;
 assert denied,'Non-member cannot complete pair';
 perform public.party_extras_action('duo_confirm',jsonb_build_object('id',duo),ka,ta);
 assert public.get_party_extras(ka,ta)#>>'{duo,status}'='active','First confirmation is not completion';
 perform public.party_extras_action('duo_confirm',jsonb_build_object('id',duo),kb,tb);
 assert public.get_party_extras(ka,ta)#>>'{duo,status}'='completed','Both confirmations complete duo';
 perform public.party_extras_action('duo_join','{}',ka,ta);
 perform public.party_extras_action('duo_join','{}',kb,tb);
 assert (public.get_party_extras(kb,tb)->>'waiting')::boolean,'Same two players are not paired again';
 perform public.party_extras_action('duo_leave','{}',ka,ta);
 assert not (public.get_party_extras(ka,ta)->>'waiting')::boolean,'Waiting can be cancelled';
 set local role authenticated;
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 perform public.party_extras_action('admin_settings','{"duos_open":false,"jukebox_open":false}');
 set local role anon;
 perform set_config('request.jwt.claim.sub','',true);
 denied:=false;
 begin perform public.party_extras_action('duo_join','{}',kc,tc); exception when others then denied:=sqlerrm='DUOS_CLOSED'; end;
 assert denied,'Closed duos block participation';
 denied:=false;
 begin perform public.party_extras_action('song_submit','{"title":"Closed","artist":"QA"}',kb,tb); exception when others then denied:=sqlerrm='JUKEBOX_CLOSED'; end;
 assert denied,'Closed jukebox blocks submissions';
 reset role;
end;
$$;
select 'PASS: privacy, identities, admin access, capsule opening, moderation, links, quota, votes, pairing and confirmations' as result;
rollback;
