-- Synthetic fixtures only; everything, including read markers, is rolled back.
begin;
set local plpgsql.check_asserts = on;
do $$
declare
  a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); ta uuid:=gen_random_uuid(); tb uuid:=gen_random_uuid();
  ka text; kb text; admin_id uuid; result jsonb; first_id text; second_id text;
  request_id uuid:=gen_random_uuid(); denied boolean; start_unread integer; page jsonb;
begin
  ka:='guest:'||a; kb:='guest:'||b;
  select user_id into admin_id from public.app_admins limit 1;
  assert admin_id is not null,'Admin fixture required';
  insert into public.guests(id,name,status) values(a,'QA Chat A','confirmed'),(b,'QA Chat B','confirmed');
  insert into public.party_identity_sessions(player_key,player_name,session_token) values(ka,'QA Chat A',ta),(kb,'QA Chat B',tb);
  update party_chat.settings set open=true where id;
  set local role anon;
  perform set_config('request.jwt.claim.sub','',true);
  denied:=false;
  begin perform * from party_chat.messages; exception when insufficient_privilege then denied:=true; end;
  assert denied,'No direct table access';
  denied:=false;
  begin perform public.get_party_chat(); exception when others then denied:=sqlerrm='IDENTITY_REQUIRED'; end;
  assert denied,'Anonymous cannot read chat';
  denied:=false;
  begin perform public.get_party_chat(ka,tb); exception when others then denied:=sqlerrm='IDENTITY_REQUIRED'; end;
  assert denied,'Wrong session cannot read';
  denied:=false;
  begin perform public.get_party_chat(ka,ta,true); exception when others then denied:=sqlerrm='NOT_ADMIN'; end;
  assert denied,'Admin flag is not authority';
  denied:=false;
  begin perform public.party_chat_action('admin_pause','{"paused":true}',ka,ta); exception when others then denied:=sqlerrm='NOT_ADMIN'; end;
  assert denied,'Guest cannot pause';
  start_unread:=(public.get_party_chat(kb,tb)->>'unread')::integer;
  result:=public.party_chat_action('send',jsonb_build_object('body','  Salut !  ','request_id',request_id,'name','Spoofed'),ka,ta);
  first_id:=result->>'id';
  assert first_id is not null,'Send returns ID';
  assert public.party_chat_action('send',jsonb_build_object('body','Salut !','request_id',request_id),ka,ta)->>'id'=first_id,'Retry is idempotent before rate limit';
  result:=public.get_party_chat(kb,tb);
  assert (result->>'unread')::integer=start_unread+1,'Other guest has an unread message';
  assert exists(select 1 from jsonb_array_elements(result->'messages') m where m->>'id'=first_id and m->>'name'='QA Chat A' and m->>'body'='Salut !' and m->>'mine'='false'),'Name is server-derived';
  assert not exists(select 1 from jsonb_array_elements(result->'messages') m where m ? 'player_key' or m ? 'request_id' or m ? 'session_token'),'No identity secrets in response';
  assert jsonb_array_length(public.get_party_chat(kb,tb,false,true)->'messages')=0,'Home gets counts only';
  denied:=false;
  begin perform public.party_chat_action('send',jsonb_build_object('body','Second','request_id',gen_random_uuid()),ka,ta); exception when others then denied:=sqlerrm='CHAT_RATE_LIMIT'; end;
  assert denied,'Server limits rapid sends';
  denied:=false;
  begin perform public.party_chat_action('send',jsonb_build_object('body',repeat('a',301),'request_id',gen_random_uuid()),kb,tb); exception when others then denied:=sqlerrm='CHAT_INVALID_BODY'; end;
  assert denied,'Server enforces max length';
  denied:=false;
  begin perform public.party_chat_action('send',jsonb_build_object('body',E' \n\t ','request_id',gen_random_uuid()),kb,tb); exception when others then denied:=sqlerrm='CHAT_INVALID_BODY'; end;
  assert denied,'Whitespace-only messages rejected';
  denied:=false;
  begin perform public.party_chat_action('delete',jsonb_build_object('id',first_id),kb,tb); exception when others then denied:=sqlerrm='CHAT_NOT_ALLOWED'; end;
  assert denied,'Cannot remove another guest message';
  perform public.party_chat_action('read',jsonb_build_object('id',first_id),kb,tb);
  assert (public.get_party_chat(kb,tb)->>'unread')::integer=0,'Read watermark clears count';
  perform public.party_chat_action('read','{"id":"0"}',kb,tb);
  assert (public.get_party_chat(kb,tb)->>'unread')::integer=0,'Delayed read cannot move watermark backwards';
  perform public.party_chat_action('delete',jsonb_build_object('id',first_id),ka,ta);
  assert not exists(select 1 from jsonb_array_elements(public.get_party_chat(kb,tb)->'messages') m where m->>'id'=first_id),'Deleted message disappears for everyone';
  perform public.party_chat_action('send',jsonb_build_object('body','Salut !','request_id',request_id),ka,ta);
  assert not exists(select 1 from jsonb_array_elements(public.get_party_chat(kb,tb)->'messages') m where m->>'id'=first_id),'Retry cannot resurrect deleted message';
  denied:=false;
  begin perform public.party_chat_action('send',jsonb_build_object('body','Again','request_id',gen_random_uuid()),ka,ta); exception when others then denied:=sqlerrm='CHAT_RATE_LIMIT'; end;
  assert denied,'Deleting does not reset rate limit';
  second_id:=public.party_chat_action('send',jsonb_build_object('body',repeat('🙂',300),'request_id',gen_random_uuid()),kb,tb)->>'id';
  assert second_id is not null,'300 Unicode characters are accepted';
  set local role authenticated;
  perform set_config('request.jwt.claim.sub',b::text,true);
  denied:=false;
  begin perform public.get_party_chat(null,null,true); exception when others then denied:=sqlerrm='NOT_ADMIN'; end;
  assert denied,'Authenticated non-admin cannot moderate';
  perform set_config('request.jwt.claim.sub',admin_id::text,true);
  assert public.get_party_chat(null,null,true)->>'open'='true','Admin can read without guest identity';
  perform public.party_chat_action('admin_delete',jsonb_build_object('id',second_id));
  perform public.party_chat_action('admin_pause','{"paused":true}');
  set local role anon;
  perform set_config('request.jwt.claim.sub','',true);
  assert public.get_party_chat(kb,tb)->>'open'='false','Pause propagated to guests';
  denied:=false;
  begin perform public.party_chat_action('send',jsonb_build_object('body','Paused','request_id',gen_random_uuid()),ka,ta); exception when others then denied:=sqlerrm='CHAT_PAUSED'; end;
  assert denied,'Pause rejects new sends';
  reset role;
  assert (select body is null from party_chat.messages where id=second_id::bigint),'Deletion removes stored text';
  update party_chat.settings set open=true where id;
  -- Synthetic old messages test stable pagination and the per-minute cap.
  insert into party_chat.messages(player_key,player_name,request_id,body,created_at)
    select ka,'QA Chat A',gen_random_uuid(),'History '||i,clock_timestamp()-interval '10 minutes' from generate_series(1,55) i;
  set local role anon;
  result:=public.get_party_chat(kb,tb);
  assert jsonb_array_length(result->'messages')=50 and result->>'more'='true','Bounded latest page';
  page:=public.get_party_chat(kb,tb,false,false,(result->>'oldest')::bigint);
  assert not exists(select 1 from jsonb_array_elements(page->'messages') x join jsonb_array_elements(result->'messages') y on x->>'id'=y->>'id'),'Cursor pages never overlap';
  reset role;
  update party_chat.messages set created_at=clock_timestamp()-interval '30 seconds' where player_key=ka;
  set local role anon;
  denied:=false;
  begin perform public.party_chat_action('send',jsonb_build_object('body','Quota','request_id',gen_random_uuid()),ka,ta); exception when others then denied:=sqlerrm='CHAT_RATE_LIMIT'; end;
  assert denied,'Per-minute quota enforced';
end;
$$;
rollback;
