begin;
do $$
declare admin_id uuid; lease uuid:=gen_random_uuid(); sid uuid:=gen_random_uuid(); result jsonb;
begin
 select user_id into admin_id from public.app_admins limit 1;
 assert admin_id is not null,'Need existing admin for the transaction-only permission tests';
 execute 'set local role anon';
 begin perform public.spotify_bridge(admin_id,'acquire','{}',lease); raise exception 'anon leaked'; exception when insufficient_privilege then null; end;
 execute 'set local role authenticated';
 begin perform public.spotify_bridge(admin_id,'acquire','{}',lease); raise exception 'authenticated leaked'; exception when insufficient_privilege then null; end;
 begin perform 1 from party_extras.spotify_connection; raise exception 'table leaked'; exception when insufficient_privilege then null; end;
 execute 'reset role';
 insert into party_extras.songs(id,player_key,player_name,title,artist) values(sid,'spotify-test-only','Fixture','Song fixture','Artist fixture');
 execute 'set local role service_role';
 begin perform public.spotify_bridge(gen_random_uuid(),'acquire','{}',lease); raise exception 'nonadmin passed'; exception when raise_exception then if sqlerrm<>'NOT_ADMIN' then raise; end if; end;
 perform public.spotify_bridge(admin_id,'acquire','{}',lease);
 begin perform public.spotify_bridge(admin_id,'acquire','{}',gen_random_uuid()); raise exception 'parallel lease passed'; exception when raise_exception then if sqlerrm<>'SPOTIFY_BUSY' then raise; end if; end;
 perform public.spotify_bridge(admin_id,'configure',jsonb_build_object('client_id',repeat('a',32)),lease);
 perform public.spotify_bridge(admin_id,'begin','{"state":"state-fixture","verifier":"verifier-fixture"}',lease);
 begin perform public.spotify_bridge(admin_id,'consume','{"state":"wrong"}',lease); raise exception 'wrong state passed'; exception when raise_exception then if sqlerrm<>'OAUTH_EXPIRED' then raise; end if; end;
 result:=public.spotify_bridge(admin_id,'consume','{"state":"state-fixture"}',lease);
 assert result->>'verifier'='verifier-fixture';
 begin perform public.spotify_bridge(admin_id,'consume','{"state":"state-fixture"}',lease); raise exception 'state replay passed'; exception when raise_exception then if sqlerrm<>'OAUTH_EXPIRED' then raise; end if; end;
 perform public.spotify_bridge(admin_id,'tokens','{"access_token":"synthetic-only","refresh_token":"synthetic-refresh","expires_at":0}',lease);
 perform public.spotify_bridge(admin_id,'release','{}',lease);
 result:=public.spotify_bridge(admin_id,'acquire','{}',lease);
 assert result->'tokens'->>'access_token'='synthetic-only','Vault roundtrip failed';
 perform public.spotify_bridge(admin_id,'claim_song',jsonb_build_object('song_id',sid,'uri','spotify:track:4iV5W9uYEdYUVa79Axb7Rh'),lease);
 begin perform public.spotify_bridge(admin_id,'claim_song',jsonb_build_object('song_id',sid,'uri','spotify:track:4iV5W9uYEdYUVa79Axb7Rh'),lease); raise exception 'duplicate passed'; exception when raise_exception then if sqlerrm<>'ALREADY_DISPATCHED' then raise; end if; end;
 perform public.spotify_bridge(admin_id,'sent',jsonb_build_object('song_id',sid),lease);
 execute 'reset role';
 assert (select status='queued' from party_extras.songs where id=sid),'Acceptance not recorded';
 begin update party_extras.songs set status='rejected' where id=sid; raise exception 'sent song rejected'; exception when raise_exception then if sqlerrm<>'SPOTIFY_ALREADY_SENT' then raise; end if; end;
 execute 'set local role service_role';
 perform public.spotify_bridge(admin_id,'disconnect','{}',lease);
 perform public.spotify_bridge(admin_id,'release','{}',lease);
 result:=public.spotify_bridge(admin_id,'acquire','{}',lease);
 assert result->'tokens'='null'::jsonb,'Disconnect retained token';
 execute 'reset role';
end;
$$;
select 'PASS: roles, admin validation, leases, OAuth state/replay, encrypted token roundtrip, duplicate dispatch and disconnect' as result;
rollback;
