-- Run inside a transaction and roll back: no real songs or playback are touched.
do $$
declare
 g uuid:=gen_random_uuid(); other_g uuid:=gen_random_uuid(); token uuid:=gen_random_uuid();
 k text; identity jsonb; sid uuid:=gen_random_uuid(); lease uuid:=gen_random_uuid();
 result jsonb; denied boolean:=false; dummy jsonb; attempt integer;
begin
 k:='guest:'||g; identity:=jsonb_build_object('player_key',k,'session_token',token);
 insert into public.guests(id,name,status) values(g,'QA guest choice','confirmed'),(other_g,'QA other guest','confirmed');
 insert into public.party_identity_sessions(player_key,player_name,session_token) values(k,'QA guest choice',token);
 update party_extras.settings set jukebox_visible=true,jukebox_open=true where id;
 update public.party_state set phase='live' where id='main';
 update party_extras.spotify_connection set lease_id=null,lease_until=null where id;
 set local role anon;
 begin perform public.spotify_guest_bridge(identity,'acquire','{}',lease); exception when insufficient_privilege then denied:=true; end;
 assert denied,'Guests must never call privileged RPC directly';
 reset role;
 set local role service_role;
 begin perform public.spotify_guest_bridge(jsonb_set(identity,'{session_token}',to_jsonb(gen_random_uuid())),'acquire','{}',lease); exception when others then assert sqlerrm='IDENTITY_REQUIRED'; denied:=false; end;
 assert not denied,'Invalid session rejected before tokens';
 result:=public.spotify_guest_bridge(identity,'acquire',jsonb_build_object('song_id',sid),lease);
 perform public.spotify_guest_bridge(identity,'prepare',jsonb_build_object('song_id',sid,'title',g::text,'artist','Artist','link','https://open.spotify.com/track/'||repeat('A',22)),lease);
 perform public.spotify_guest_bridge(identity,'claim_song',jsonb_build_object('song_id',sid,'uri','spotify:track:'||repeat('A',22)),lease);
 perform public.spotify_guest_bridge(identity,'sent',jsonb_build_object('song_id',sid),lease);
 perform public.spotify_guest_bridge(identity,'release','{}',lease);
 result:=public.spotify_guest_bridge(identity,'acquire',jsonb_build_object('song_id',sid),lease);
 assert result->>'dispatch'='sent','Same request must return sent for idempotency';
 perform public.spotify_guest_bridge(identity,'release','{}',lease);
 reset role;
 assert (select status='queued' from party_extras.songs where id=sid),'No admin acceptance required';
 assert (select count(*)=1 from party_extras.songs where player_key=k),'No duplicate proposal';
 insert into party_extras.songs(player_key,player_name,title,artist) values(k,'QA',g::text||' legacy',''),(k,'QA',g::text||' three','');
 select id into sid from party_extras.songs where title=g::text||' legacy';
 set local role service_role;
 result:=public.spotify_guest_bridge(identity,'acquire',jsonb_build_object('song_id',sid),lease);
 perform public.spotify_guest_bridge(identity,'prepare',jsonb_build_object('song_id',sid,'title',g::text||' corrected','artist','Correct Artist','link','https://open.spotify.com/track/'||repeat('B',22)),lease);
 perform public.spotify_guest_bridge(identity,'claim_song',jsonb_build_object('song_id',sid,'uri','spotify:track:'||repeat('B',22)),lease);
 perform public.spotify_guest_bridge(identity,'release','{}',lease);
 result:=public.spotify_guest_bridge(identity,'acquire',jsonb_build_object('song_id',sid),lease);
 assert result->>'dispatch'='uncertain','Unknown queue acknowledgement cannot be resent';
 perform public.spotify_guest_bridge(identity,'release','{}',lease);
 denied:=false;
 begin perform public.spotify_guest_bridge(identity,'acquire',jsonb_build_object('song_id',gen_random_uuid()),lease); exception when others then denied:=sqlerrm='SONG_LIMIT'; end;
 assert denied,'Fourth proposal blocked';
 reset role;
 assert (select count(*)=3 from party_extras.songs where player_key=k),'Repair uses no extra quota';
 insert into party_extras.songs(id,player_key,player_name,title,artist) values(other_g,'guest:'||other_g,'QA other',other_g::text,'');
 set local role service_role;
 denied:=false;
 begin perform public.spotify_guest_bridge(identity,'acquire',jsonb_build_object('song_id',other_g),lease); exception when others then denied:=sqlerrm='SONG_NOT_READY'; end;
 assert denied,'Another guest proposal is inaccessible';
 reset role;
 update party_extras.settings set jukebox_open=false where id;
 set local role service_role;
 denied:=false;
 begin perform public.spotify_guest_bridge(identity,'acquire',jsonb_build_object('song_id',sid),lease); exception when others then denied:=sqlerrm='JUKEBOX_CLOSED'; end;
 assert denied,'Global off switch enforced';
 reset role;
 update party_extras.settings set jukebox_open=true where id;
 update party_extras.spotify_guest_limits set requests=20 where player_key=k;
 set local role service_role;
 denied:=false;
 begin perform public.spotify_guest_bridge(identity,'acquire',jsonb_build_object('song_id',sid),lease); exception when others then denied:=sqlerrm='SEARCH_RATE_LIMIT'; end;
 assert denied,'Rate limit enforced before Spotify';
 reset role;
end;
$$;
select 'PASS: guest identity, service-only privileges, automatic acceptance, idempotency, legacy repair at quota, ownership, close and rate limits' as result;
